name: Build Windows Executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --name TelegramBackdoor main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: TelegramBackdoor
        path: dist/TelegramBackdoor.exe
